# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcyradm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailusers',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
