# Generated by Django 3.0.7 on 2020-12-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcyradm', '0002_mailusers_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
